name: Cerkour
version: '1.0-SNAPSHOT'
main: me.cerdax.cerkour.Cerkour
api-version: '1.8.8'
commands:
  gg:
    description: A simple GG command
    usage: /<command>
  map:
    description: Map handling
  join:
    description: Join a map
  leave:
    description: Leave a map
  profile:
    description: Edit profile stats
  spawn:
    description: Teleports you to spawn
  leaderboard:
    description: Displays leaderboard for that map
    aliases: [lb]
  practice:
    description: Enters practice mode
    aliases: [prac]

